export const FETCH_POSTS = 'FETCH_POSTS';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_POSTS = 'FILTER_POSTS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_CANCELLED = 'DELETE_POST_CANCELLED';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_CONFIRMED = 'DELETE_POST_CONFIRMED';
