export const FETCH_POSTS = 'FETCH_POSTS';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_POSTS = 'FILTER_POSTS';
